# Value populated by PROJECT_NAME
# set(CPACK_PACKAGE_NAME MyProj)

# Value populated by CMAKE_PROJECT_DESCRIPTION
# set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Example project")

# Base package settings
set(CPACK_PACKAGE_VENDOR ${PROJECT_COMPANY_NAME})
set(CPACK_PACKAGE_DIRECTORY distribution)
set(CPACK_PACKAGE_INSTALL_DIRECTORY ${CPACK_PACKAGE_NAME})
set(CPACK_SOURCE_PACKAGE_FILE_NAME "${PROJECT_NAME}-${CMAKE_PROJECT_VERSION}")
set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(CPACK_VERBATIM_VARIABLES YES)
set(CPACK_MONOLITHIC_INSTALL TRUE)

# Package resources
set(CPACK_RESOURCE_FILE_WELCOME ${SHARED_PACKAGING_DIR}/Welcome.txt)
set(CPACK_PACKAGE_DESCRIPTION_FILE ${SHARED_PACKAGING_DIR}/Description.txt)
set(CPACK_RESOURCE_FILE_README ${SHARED_PACKAGING_DIR}/Readme.txt)
set(CPACK_RESOURCE_FILE_LICENSE ${SHARED_PACKAGING_DIR}/License.txt)

# This option will change the mount drive icon used.
# set(CPACK_PACKAGE_ICON ${SHARED_PACKAGING_DIR}/dmg/volume.icns)

# macOS settings for DragNDrop generator
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE OFF)
set(CPACK_DMG_BACKGROUND_IMAGE "${SHARED_PACKAGING_DIR}/dmg/AppDMGBackground.tiff")
set(CPACK_DMG_DS_STORE_SETUP_SCRIPT "${SHARED_PACKAGING_DIR}/dmg/AppDMGSetup.scpt")
set(CPACK_DMG_VOLUME_NAME "${PROJECT_NAME}")

# Windows settings for NSIS generator
set(CPACK_NSIS_DISPLAY_NAME ${PROJECT_NAME})
set(CPACK_NSIS_PACKAGE_NAME ${CPACK_PACKAGE_NAME})
set(CPACK_NSIS_MANIFEST_DPI_AWARE true)
set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL YES)
set(CPACK_NSIS_MUI_ICON "${ASSETS_ICONS_SOURCE_FOLDER}/icon.ico")
set(CPACK_NSIS_INSTALLED_ICON_NAME "${ASSETS_ICONS_SOURCE_FOLDER}/icon.ico")
set(CPACK_NSIS_MUI_UNIICON ${SHARED_PACKAGING_DIR}/nsis\\\\uninstall_icon.ico)
set(CPACK_NSIS_MUI_HEADERIMAGE ${SHARED_PACKAGING_DIR}/nsis\\\\nsis_header.bmp)
set(CPACK_NSIS_MUI_WELCOMEFINISHPAGE_BITMAP ${SHARED_PACKAGING_DIR}/nsis\\\\nsis_install_welcome.bmp)
set(CPACK_NSIS_MUI_UNWELCOMEFINISHPAGE_BITMAP ${SHARED_PACKAGING_DIR}/nsis\\\\nsis_uninstall_welcome.bmp)

# Linux DEB settings
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
# set(CPACK_DEBIAN_PACKAGE_DEPENDS "libsdl2-2-0")
# Section list: https://packages.debian.org/unstable/
set(CPACK_DEBIAN_PACKAGE_SECTION Miscellaneous)
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Maintainer Name")

# Define how to install and uninstall start menu entries on Windows
set(CPACK_NSIS_CREATE_ICONS_EXTRA
  "CreateShortCut '$SMPROGRAMS\\\\$STARTMENU_FOLDER\\\\${PROJECT_NAME}.lnk' '$INSTDIR\\\\bin\\\\${PROJECT_NAME}.exe'")
set(CPACK_NSIS_DELETE_ICONS_EXTRA
  "Delete '$SMPROGRAMS\\\\$START_MENU\\\\${PROJECT_NAME}.lnk'")

# Generator selection per platform
if (CMAKE_SYSTEM_NAME STREQUAL "Windows")
  set(CPACK_GENERATOR ZIP NSIS)
elseif (CMAKE_SYSTEM_NAME STREQUAL "Darwin")
  set(CPACK_GENERATOR TGZ DragNDrop)
elseif (CMAKE_SYSTEM_NAME STREQUAL "Linux")
  set(CPACK_GENERATOR TGZ DEB)
else ()
  set(CPACK_GENERATOR TGZ)
endif ()

include(CPack)